dependencies:
  - name: catalog
    version: '2.1.0'
    repository: 'file://../catalog'

  - name: data
    version: '2.1.1'
    repository: 'file://../data'
    alias: internal-data

    
  - name: data
    version: '2.1.1'
    repository: 'file://../data'


  - name: dashboard
    version: '2.1.0'
    repository: 'file://../dashboard'

  - name: edge
    version: '2.1.0'
    repository: 'file://../edge'

  - name: jwt
    version: '2.1.0'
    repository: 'file://../jwt'

  - name: jwt
    version: '2.1.0'
    repository: 'file://../jwt'
    alias: internal-jwt

  - name: slo
    version: '2.1.0'
    repository: 'file://../slo'

  - name: gm-control-api
    repository: 'file://../gm-control-api'
    version: '2.1.0'

  - name: control
    repository: 'file://../control'
    version: '2.1.0'

  - name: spire
    repository: 'file://../spire'
    version: '2.1.0'
    condition: global.spire.enabled
